### ISSUE TITLE
Quoting attributes

### ISSUE THREAD

**Issue by sanmai-NL** [dtolnay/quote#80] opened 2018-09-07 12:41 UTC
Quoting at least one type of attribute seems not to work inside `quote!`. I couldn’t find documentation about this. Apparently the `cfg` attribute is evaluated in the context of the crate that contains the quasi-quoted code (B) rather than the crate that uses the macro wrapping the quasi-quoted code (A).
```rust
#[cfg(feature = "no_std")] use alloc::string::String;
```
This will lead to a compilation error when A is `no_std` and B is not.

**Comment by dtolnay** [comment] 2018-09-07 17:02
This does not match my understanding of how `quote!` works. Could you provide a minimal example (lib.rs and Cargo.toml for the macro B, main.rs and Cargo.toml for A) that reproduces this behavior?

Code inside of `quote!` will be inserted at the expansion site in A as if written there by the user. If that code contains a cfg referring to `feature = "no_std"`, that is controlled by a `no_std` feature in A.

**Closed** 2018-09-29 22:30 UTC

**Comment by sanmai-NL** [comment] 2018-10-15 13:56
In the case of a `no_std` + `alloc` crate calling a procedural macro exported by a usual crate, compilation fails.

Example code:
https://github.com/lfairy/maud/pull/158/commits/67211343550c5ed502359518e02cd2b5793b7c23

Error happens here:
https://github.com/lfairy/maud/blob/365d0ab956c8cf5db9d027c11b052d7e201e63d6/maud_macros/src/lib.rs#L50-L55
```
error[E0433]: failed to resolve. Use of undeclared type or module `String`                                                                                                                                                                                  
  --> maud/tests/no_std.rs:13:13                                                                                                                                                                                                                            
   |                                                                                                                                                                                                                                                        
13 |     let _ = html!((owned));                                                                                                                                                                                                                            
   |             ^^^^^^^^^^^^^^ Use of undeclared type or module `String`                                                                                                                                                                                   
                                                                                                                                                                                                                                                            
error[E0412]: cannot find type `String` in this scope                                                                                                                                                                                                       
  --> maud/tests/no_std.rs:13:13                                                                                                                                                                                                                            
   |                                                                                                                                                                                                                                                        
13 |     let _ = html!((owned));                                                                                                                                                                                                                            
   |             ^^^^^^^^^^^^^^ not found in this scope                                                                                                                                                                                                     
help: possible candidates are found in other modules, you can import them into scope                                                                                                                                                                        
   |                                                                                                                                                                                                                                                        
7  | use alloc::prelude::String;                                                                                                                                                                                                                            
   |                                                                                                                                                                                                                                                        
7  | use alloc::string::String;                                                                                                                                                                                                                             
   |                                                                                                                                                                                                                                                        
```

So @dtolnay, maybe you’re right in general, but is this an instance of https://github.com/rust-lang/rust/issues/54863?

**Comment by dtolnay** [comment] 2018-10-15 15:09
It's actually not from there, it is from [*maud_macros/src/generate.rs#L86*](https://github.com/lfairy/maud/blob/365d0ab956c8cf5db9d027c11b052d7e201e63d6/maud_macros/src/generate.rs#L86). This is a bug in maud_macros because it refers to the type `String` without an absolute path. All macros (macro_rules and procedural macros) should be referring to library types with their full path.

Check out serde_derive for an example of a procedural macro that works equally well from std and no_std crates.

**Comment by sanmai-NL** [comment] 2018-10-15 15:15
@dtolnay: Thanks for your advice. Could you please share how you debugged this? I’m looking at compiler options to expand procedural macros or use other facilities to debug issues ...

**Comment by dtolnay** [comment] 2018-10-15 18:08
I ran `cargo expand --test no_std` to see the expanded code. https://github.com/dtolnay/cargo-expand

**Comment by lfairy** [comment] 2018-10-20 02:54
Note that Maud uses the built-in [`quote!`](https://doc.rust-lang.org/nightly/proc_macro/macro.quote.html) macro, not the one defined in this repo.

But I agree with @dtolnay that using an absolute path is a good idea.
