### ISSUE TITLE
diesel is currently broken due to sealing of Spanned

### ISSUE THREAD

**Issue by tsharp** [dtolnay/quote#242] opened 2023-03-13 05:37 UTC
Heya - it looks like the quote crate dependency has broken diesel!

I am requesting/recommending that this change be rolled back and saved for either a major or minor version update rather than a patch update to allow developers to understand what version may/probably contain breaking changes.

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html?search=#specifying-dependencies
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html?search=#tilde-requirements

See additional rust documentation on SemVer here:
https://doc.rust-lang.org/cargo/reference/semver.html#change-categories

**Comment by dtolnay** [comment] 2023-03-13 05:54
Duplicate of #241.

**Closed by dtolnay** 2023-03-13 05:54 UTC
