### ISSUE TITLE
Shall I support embedding Rust code to be executed during compilation within the quote!{} blocks?

### ISSUE THREAD

**Issue by vi** [dtolnay/quote#178] opened 2021-02-24 15:51 UTC
To be able to turn e.g.

```rust
#[proc_macro]
pub fn qqq(_: TokenStream) -> TokenStream {
    let mut lol_content = proc_macro2::TokenStream::new();
    for _ in 0..10 {
        lol_content.extend(quote::quote! {
            println!("HW");
        })
    }
    
    let mut ror_content = proc_macro2::TokenStream::new();
    for _ in 0..3 {
        ror_content.extend(quote::quote! {
            println!("GW");
        })
    }

    (quote::quote! {
        fn lol() {
            #lol_content
        }

        fn ror() {
            #ror_content
        }
    }).into()
}
```

into

```rust
#[proc_macro]
pub fn qqq(_: TokenStream) -> TokenStream {
    (quote::quote! {
        fn lol() {
            #{
                let mut content = proc_macro2::TokenStream::new();
                for _ in 0..10 {
                    content.extend(quote::quote! {
                        println!("HW");
                    })
                }
                content
            }
        }

        fn ror() {
            #{
                let mut content = proc_macro2::TokenStream::new();
                for _ in 0..3 {
                    content.extend(quote::quote! {
                        println!("GW");
                    })
                }
                content
            }
        }
    }).into()
}
```

**Comment by dtolnay** [comment] 2021-02-24 18:53
Closing as a duplicate of #10 and lots of other issues/pull requests in the history of this repo. I am not interested in having this.

**Closed by dtolnay** 2021-02-24 18:53 UTC

**Comment by vi** [comment] 2021-02-24 19:02
Maybe explicit decision to not have `#{}` (with a link to #10 and [this comment](https://github.com/dtolnay/quote/pull/88#pullrequestreview-180577592)) shall be included in README, as I see that this is somewhat common feature request.
