### ISSUE TITLE
Error: the trait `quote::ToTokens` is not implemented for `syn::File`

### ISSUE THREAD

**Issue by AchalaSB** [dtolnay/quote#138] opened 2019-11-21 11:00 UTC
I'm trying to use `quote` to get AST for my code. but it is giving an error. 
here is my code
```
#[macro_use]
extern crate quote;
extern crate syn;

fn main() {
        let source = r#"
            fn main() {
                println!("hello");
            }
        "#;
        let syntax = syn::parse_file(source).unwrap();
        println!("{:#?}\n", quote!(#syntax)); 
}
```
error log
```
error[E0277]: the trait bound `syn::File: quote::ToTokens` is not satisfied
  --> src/main.rs:20:20
   |
20 |     println!("{}", quote!(#syntax));
   |                    ^^^^^^^^^^^^^^^ the trait `quote::ToTokens` is not implemented for `syn::File`
   |
   = note: required by `quote::ToTokens::to_tokens`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```
Thanks

**Comment by dtolnay** [comment] 2019-11-21 16:27
I can't reproduce this. The same code in the playground works.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ae8912157f29b384b5532623027e82e8

**Comment by AchalaSB** [comment] 2019-11-22 03:45
Yes its working in playground. but in in my VScode. checked with different system its not working.
Getting same error. Tried in rust v1.38, 1.39 and nightly v1.41 as well.

**Comment by dtolnay** [comment] 2020-01-15 20:32
Sorry, closing because I don't think I will be able to help with this without a way to reproduce.

**Closed by dtolnay** 2020-01-15 20:32 UTC

**Comment by taiki-e** [comment] 2020-01-16 08:44
looks like this is the similar issue as https://github.com/taiki-e/syn-serde/issues/10.
so, this can be reproduced by using incompatible version or git dependencies.

e.g.:

```toml
[dependencies]
syn = "1"
quote = "0.4"
```
or
```toml
[dependencies]
syn = "1"
quote = { version = "1", git = "https://github.com/dtolnay/quote" }
```

one of the other possible causes is a bug of rls-vscode: https://github.com/rust-lang/rls-vscode/issues/98 (vscode doesn't reflect the update of the dependencies)

**Comment by matt-schrader** [comment] 2020-02-19 04:33
I ran into this today and can confirm it is resolved on master branch.
