### ISSUE TITLE
Quote expressions

### ISSUE THREAD

**Issue by timothee-haudebourg** [dtolnay/quote#190] opened 2021-10-12 18:47 UTC
I often need to quote the result of an expression, in particular (but not only) to quote the field of a structure instance. This forces me to use a temporary variable to store the result of the expression (or a reference to the field) before quoting. Would it be possible to instead have construct to quote expressions?

What I'm doing now:
```rust
let tmp = expr;
quote! { ... #tmp ... }
```

What I would prefer:
```rust
quote! { #{ expr } }
```

**Comment by dtolnay** [comment] 2021-10-12 21:01
Closing as a duplicate of #10 and lots of other issues/pull requests in the history of this repo. I am not interested in having this.

**Closed as completed by dtolnay** 2021-10-12 21:01 UTC
